fix: correctly use merlin's pipeline
ocaml/ocaml-lsp pull request #904
Opened 2022-11-04 03:33 UTC by rgrinberg

do not reuse pipelines unless we are using the same pipeline multiple
times in a row

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

ps-id: 383efc92-8d86-4d09-b01a-16fcf8c0a0d0

2022-11-04 10:47 UTC, ulugbekna requested changes
Looks correct. Indeed fixes the go-to-definition for me.

Noteworthy: there's `Mpipeline.make` used in `action_type_annotate.ml`. Could this trip up `Single_pipeline`? I couldn't reproduce the initial bug anyway.

2022-11-04 10:47 UTC, ulugbekna commented on CHANGES.md
> +- Fix random requests failing after switching documents (#901, fixes #898)
```suggestion
- Fix random requests failing after switching documents (#904, fixes #898)
```

2022-11-04 16:22 UTC, rgrinberg commented
>  there's Mpipeline.make used in action_type_annotate.ml. Could this trip up Single_pipeline? I couldn't reproduce the initial bug anyway.

It should be fine b/c it creates the pipeline inside the merlin thread.

2022-11-05 16:54 UTC, ulugbekna commented
Shall we merge this?

2022-11-05 16:55 UTC, rgrinberg commented
Let me try and fix the tests.

Rudi.
On Nov 5, 2022, 10:54 AM -0600, Ulugbek Abdullaev ***@***.***>, wrote:
> Shall we merge this?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-05 21:50 UTC, merged